### ISSUE TITLE
actxserver('Imaris.Application')  no longer work after Imaris 7.2.3

### ISSUE THREAD

**Issue by rmd13** [lucadellasantina/ObjectFinder#3]
The COM interface does not work after  Imaris 7.2.3.

**Comment by lucadellasantina** [comment]
This bug is fixed in ObjectFinder version 5.12.

Now users can select whether inspect the objects with "Bitplane Imaris (7.2.3 or older)" or with "Bitplane Imaris (7.2.4 or newer)" the former uses COM interface to communicate with Imaris, the latter uses Java's ImarisLib.jar (formerly ICE Imaris connector).
